### ISSUE TITLE
Rework "College High School Ask" on the USTEventRegister.page

### ISSUE THREAD

**Issue by jacebryan** [SFDO-Community/Summit-Events-App#11]
When I check the "I can't find my High School" checkbox on the Registration form I am unable to move to the next screen. It looks like the page is still requiring a value to be present in the "High School Attended" search field.

Looking at the [USTEventRegister.page](https://github.com/tcdahlberg/USTEventsDX/blob/master/force-app/main/default/pages/USTEventRegister.page) I see the reference to both fields but not seeing where the enforcement is being removed if the checkbox is set to true.

**Comment by tcdahlberg** [comment]
This functionality does not exist (was commented out) in this iteration of the event app. It will have to be tied to a datasource for High schools in EDA (not EnrollmentRx like it was before). That being said an open text field for "I can't find my school" should work even without the school look-up. A more immediate step would be to replace the high school report with an regular text input.

**Comment by jacebryan** [comment]
I see. So for now, since no field exists on the UST Event to capture a list of high schools and/or colleges, users should leave the value of "College High School Ask" = None or Don't ask. Is this correct?

**Comment by tcdahlberg** [comment]
Yes, for now. It's broken functionality that needs to be reworked. To be clear, it does work in that mystical other event app we have running in our EnrollmentRx production org at St. Thomas :).

**Comment by jacebryan** [comment]
Feel free to update the label from Bug to Enhancement if that is how you see this Issue being reworked in the future.

**Comment by rdblake21** [comment]
I believe that this got refactored in @tcdahlberg coding of how it happens with the SLDS.

Thad, when this is committed, please close

**Comment by rdblake21** [comment]
This got pulled out of the registration page and is not in the page layout.  This needs to be refactored to be in alignment with EDA as it is school specific.  It's currently suggested at individuals ask in a free form question about school of attendance.
