### ISSUE TITLE
Why is the UST Event Host record type "Counselor" missing a page layout?

### ISSUE THREAD

**Issue by jacebryan** [SFDO-Community/Summit-Events-App#12]
I've noticed that there are page layouts in the package for all UST Event Host record types except for Counselor. Is this on purpose?

**Comment by tcdahlberg** [comment]
I may have missed this one when I created this version of the Event app. I would like to give the hosting feature some BA work and recoding love as I think it could be much better.

**Comment by jacebryan** [comment]
Feel free to update the label from Question to Enhancement if that is how you see this Issue being reworked in the future.

**Comment by rdblake21** [comment]
Closing this ticket as "Hosts" will get some rework down the road.  Need more requirements on Summit Events Host before we answer questions on functionality.
