### ISSUE TITLE
Rework the UST Event Academic Program List to include options for EDA Academic Programs

### ISSUE THREAD

**Issue by jacebryan** [SFDO-Community/Summit-Events-App#14]
Currently, the UST Event object has a multi-select picklist field called Academic Program List. In order to use this field, an admin has to enter (and keep updated) a manual list of Academic Programs in order for it to be used as part of the Registration process. In its current state, the need to manually update (and keep updated) a list of Academic Programs could lead to discrepancies between what Academic Programs are stored in Salesforce (EDA) vs. what is shown in the UST Event object.

Use Case:

Let's say I want to create an Event using the Undergraduate record type AND Applicant Type = First-Year. This indicates to me that the audience for this event will surround 1) Juniors and/or Seniors in High School and 2) Those who have already graduated high school but have yet to earn an undergraduate degree.

I set the "Ask Registrant Program Of Interest" field to any of the "Ask..." values. Setting one of those values indicates that the "Program of Interest" field will be displayed to the registrant during registration.

I then see 2 options that define how Academic Programs are displayed during Registration: 

- I can select from a list of existing Academic Program records in EDA

- I can create a custom list of Academic Programs

**Comment by tcdahlberg** [comment]
You've hit the nail on the head (or the heda... or eda)! Maintaining these dependent picklists for programs has always been troublesome. It grew out of a time where our institutional data was not in the place it needed to be yet. I am excited to have this figured out.

**Comment by rdblake21** [comment]
I anticipate that this won't be a part of the sprints at this point.  I'm trying to associate issues with Project boards so we don't have a ton of issues without any structure to it.  

@jacebryan, @jimhubert and @tcdahlberg , is this a priority for SPrint One?  Or does it make sense for it to be a topic of conversation at Sprint two or three?

**Comment by rdblake21** [comment]
From a duplicate Issue #37:

I believe we should use the EDA functionality for Academic Programs - "An Academic Program in EDA is simply an Account with a specific record type called 'Academic Program'." 

https://powerofus.force.com/s/article/EDA-Create-Academic-Programs-and-Program-Enrollments

**Comment by rdblake21** [comment]
This will need to be a part of EDA functionality, per previous comments.  INsitutiions can currrently use the global picklist if it is something they'd like to maintain.  Ideally, it would capture those programs within your org, but the Global picklist values are the best route at this point.
