### ISSUE TITLE
USTEventRegister.page: List of Academic Programs are not displaying

### ISSUE THREAD

**Issue by jacebryan** [SFDO-Community/Summit-Events-App#15]
After assigning values to the "Academic Program List" on the Event record I am not seeing those values displayed on the web form under Program of Interest. There are no values appearing in the list on the web form period.

Until this issue is resolved users should set the value of "Ask Registrant Program Of Interest" on the Event record to "--None--" or "Do not ask".

**Comment by rdblake21** [comment]
This will need to get resolved in the initial setup documentation #33 and #14

**Comment by rdblake21** [comment]
This will need to be a part of EDA functionality, per previous comments. Institution's can currently use the global picklist if it is something they'd like to maintain. Ideally, it would capture those programs within your org, but the Global picklist values are the best route at this point.
