### ISSUE TITLE
Admin - How to Configure Permissions for End Users and Documenting What is in Admin Permission Set

### ISSUE THREAD

**Issue by jacebryan** [SFDO-Community/Summit-Events-App#16]
1) There is a delivered "Summit Events Admin" permission set, document what is included in this permission set.

2) Define what is needed to clone the Summit Event Admin permission set to create a custom permission set for users in your orginization.  This can include items such as setup record types, page layouts and Field Level Security (FLS). This information should be detailed out in the end user documentation. Highly recommend addressing any fields and/or related list that should be added to page layouts too.

**Comment by rdblake21** [comment]
#33 should have this factored into it.

**Comment by ShaynaStockton** [comment]
[https://docs.google.com/document/d/1wIUiHWTZzRZ6qbjt3ZDApCUt8LjDh-6RBPYOFk6u1hU/edit](url)
Beginning on this

**Comment by rdblake21** [comment]
https://sfdo-community-sprints.github.io/summit-events-app-documentation/docs/Getting-Started/Installing/#apply-permission-sets

Captured here
