### ISSUE TITLE
Compassionate Story Tellers wanted!

### ISSUE THREAD

**Issue by jacebryan** [SFDO-Community/Summit-Events-App#18]
If you are interested in creating compassionate storytelling around the usage of this App please post a comment below. 

Take a look at what has already been stared around this effort in the [wiki](https://github.com/tcdahlberg/USTEventsDX/wiki/Test-out-the-USTEvents-App-in-your-Scratch-Org).

**Comment by rdblake21** [comment]
Compassionate story documentation
- [ ] User Experience
- [ ] Guest Experience

**Comment by rdblake21** [comment]
@jacebryan from your perspective, is the compassionate story tell supposed to lead you to through the "setup".  Looking at the Wiki you already put together the the Guest User experience story is great, leading to installation of it all.

Is the idea hear to guide an individual to the setup process or to give the use cases for marketing purposes (or both?).  I'm wanting to formulate the story for the User experience on setting up the event itself, once already installed to show the ease and pace of actually spinning up an event.

Let me know what you think

**Comment by rdblake21** [comment]
[Administrative User Story.docx](https://github.com/tcdahlberg/Summit-Events-App/files/4282686/Administrative.User.Story.docx)

Initial draft of a user story with setup from an administrative perspective.  Answering: What's the experience in setting something up.

**Comment by dwhitig** [comment]
@rdblake21 I went to look at your Administrative User Story doc and it shows as not found.  Should we add this as a topic at our next meeting?  The wiki link provided by Jace just took me to a blank Create New Page.

**Comment by rdblake21** [comment]
Changed documentation style and this isn't specifically needed
