### ISSUE TITLE
UST Event Appointment Types: Chosen State value of "None" is not functioning as expected

### ISSUE THREAD

**Issue by jacebryan** [SFDO-Community/Summit-Events-App#19]
When creating an Events Appointment Type I set the Chosen State = "None". 

I anticipate that by doing so the Event Appointment(s) will need to be manually selected on the form by the registrant rather than automatically added (based on the help text for Chosen State.) This is not the case. 

Setting the Chosen State = "None" automatically selects the appointments for the registrants on the form.

**Comment by rdblake21** [comment]
This has been resolved and not an issue.  Unable to located pull request that fixed this bug.
