### ISSUE TITLE
Update Contact fields on Matching, Not Just on New Contact Creation

### ISSUE THREAD

**Issue by jimhubert** [SFDO-Community/Summit-Events-App#192]
Our current functionality is that if Contact Matching finds an existing record in Salesforce it matches it to the Summit Events Registration record but does not make any changes to that Contact record - the only way the Custom Metadata mapping fields or hardcoded Summit Events Registration fields are added to a Contact record is if a new Contact record is created.   This issue is a request to automatically update selected fields on the Contact record using the Custom Metadata mappings.

The use case for this request was presented by Bryn Scott during the September 2020 sprint:
"In our custom integrations - if the Mailing Address is empty or only zip code - then we update the Address if more info in the new record. Doing that since a lot of mailings are done based on Zip/State - so we are wanting to capture that if provided.  Don't update the Address if it already exists.  

Mailing Address is a challenge since sees separate fields and not as a whole address.  Meaning if existing address is 123 Main Street, Washington DC 20005.  And new address is just Alexandria, Va 22302.  We would not want to just plop the City/State/Zip because 123 Main would then be in Alexandria VA not DC.

An option to consider:  On update - do you want to overwrite existing data (if incoming data is not blank) OR overwrite even if incoming is blank OR don't overwrite existing data?

**Comment by rdblake21** [comment]
@jimhubert and @Scarrien worked in this with great feedback from @walt0019.  This is in the core and has documentation associated to it.

#118 
#217 
#227 
#142 

Documentation of full process is in development, but can also be found in the [Wiki page](https://github.com/SFDO-Community-Sprints/Summit-Events-App/wiki/0c--%E2%80%93-Setup-Contact-Matching)

**Comment by rdblake21** [comment]
Additional note: improvements are coming with additional documentation
