### ISSUE TITLE
Allow person creating the event to determine the text that displays for questions 

### ISSUE THREAD

**Issue by jimhubert** [SFDO-Community/Summit-Events-App#204]
In the "Options" section of the Event object the person creating the event can decide if questions are asked to the person filling out the registration form by selecting the questions they want to ask.  However they do not have any control of the question text that appears on the registration page because the question text is hard-coded into the product. 

This is a problem because it reduces the flexibility of the product. An example of this problem is the "Ask Student Type" field.   Because Student Type does not apply to all types of organizations an Admin could decide to change the Field Label for this field to something like "Person Type" which changes the field name they see on the Event page layout.  However the question the registrant sees will not display this change value and will always say "Student Type" because this value is hard-coded and can't be edited by the person creating the event. 

We already have the ability for the event creator to determine the question text that appears on the registration form for the 5 "Additional Questions", we need to add the ability for the event creator to customize the question text for the other questions that appear on the event registration form as well.

**Solution:**

- Added Label fields to Summit Events Object
- Events have a default value so they don't require an end user to populate them upon creating an event
- An end user can edit the default value to replace what shows up on the Registration Page

**Comment by jimhubert** [comment]
FYI @walt0019 , I believe you have a need for this functionality for UDAR, please add your comments and details on that use case here.

**Comment by GardinerMatt** [comment]
This would be useful for BYU also. Our admissions department has asked about changing Label text already. For now I've just been planning to rewrite the labels with JavaScript after they're loaded -- which is not ideal.

**Comment by jimhubert** [comment]
I think that "Custom Labels" could be the best solution, more details on this at https://help.salesforce.com/articleView?id=cl_about.htm&type=5

Custom Label, Custom Metadata Types, and Custom Settings are 3 possible methods for this, here is an overview of these methods to help analyze which one may be best:
https://trailblazers.salesforce.com/answers?id=9063A000000q12AQAQ
https://jenwlee.com/2017/03/28/did-i-just-see-you-hardcode-a-salesforce-id-aw-hell-no/

Notes on a couple of items that are not what we are discussing above:
*  "Field Labels" that users see on an internal Salesforce page have a 40 character limit so are not a good solution for this https://help.salesforce.com/apex/HTViewSolution?id=000270252&language=en_US#:~:text=The%20current%20character%20limit%20for,if%20it%20has%20a%20namespaceprefix.  In addition Field Labels are for internal users, while the questions text is for external users on the event registration page.
* If an organization wants to change the internal Field Label name displaying on the Summit Events managed package fields they can already do this with existing functionality by using Translation Workbench "overrride" as described at https://advancedcommunities.com/how-to-translate-rename-custom-labels-and-fields-in-managed-packages/#:~:text=You%20can%20only%20override%20labels,one%20language%2C%20select%20a%20language.

**Comment by JohnnyMac99** [comment]
Although Custom Labels will work, and it is the quickest way to eliminate hardcoded values in VisualForce, the event coordinator will have to:
1. Set the question choice on the Event record
2. Set the Online Registration String as a custom label (granted this only needs to be done once)
 - not typically something that a non-admin does
 - requires admin rights and some training or an admin to do it for them
3. Preview the Site to see the final product
4. This still limits the question labels to a single value across the org when on some event you may want it to ask X and on the next event Y


There is a model we have built and proven. It would require more refactoring but it would address other issues like being able to have an unlimited number of questions, and be able to tailor the questions to the event: (I can provide a quick demo)
- Remove all Question fields from the Event Object and create them as child records. In my model the child of Summit Event would be "Assigned Question Group"
- Assigned Question Group is a junction object between Contact and "Question Group"
- "Question Group" is just a container for "Questions" but it does have a name you can use a header to group questions
- "Questions" have all the details about the question being asked plus where in the database you want to map the answer

It's completely extensible and flexible but again the refactor is much larger. Maybe it is do the above and plan for this?

**Comment by tiagoruivo** [comment]
Created branch "feature/dynamic-labels-registration-page" with the results of this

**Comment by tcdahlberg** [comment]
Included in beta release 0.27.0.1

**Comment by tcdahlberg** [comment]
Included in production release 0.27.0.1
