### ISSUE TITLE
Contact Matching within Summit Events - Manual intervention when matching on multiples

### ISSUE THREAD

**Issue by walt0019** [SFDO-Community/Summit-Events-App#211]
Hi Awesome Developers and Community Members!

We are using native Salesforce Duplicate and Matching Rules in coordination with Summit Events.  It works great, but I raise one use case where I'm hoping to get help.  When Salesforce finds more than one possible match on the criteria, can it create the Registration record and have a person come in later and manually match it to a Contact?  I explain more the use case below.

Use Case - Multiple Matches
We have multiple, but different people named John Sullivan in the Class of 1950 for example.
![image](https://user-images.githubusercontent.com/57462572/97720854-c3f59400-1a96-11eb-85b2-df46a2135557.png)

I register for the Event providing First Name, Last Name, Class Year and other data that is part of our Matching Rules.
![image](https://user-images.githubusercontent.com/57462572/97721075-00c18b00-1a97-11eb-921a-8904e2e4cced.png)

The Summit Events registration processes and connected to one of the Contact records.  I am not sure how it picked the record, but the ideal scenario would be for someone to come through and matched it with a finer examination.

If I created this Contact record within Salesforce on the Contact object, I would receive the Alert (if selected within the Duplicate rule) and the possible matches. 

![image](https://user-images.githubusercontent.com/57462572/97721430-6b72c680-1a97-11eb-837a-1472ad7eff05.png)

![image](https://user-images.githubusercontent.com/57462572/97721484-79284c00-1a97-11eb-8830-caf006af6db8.png)

Would there be any way to block the Contact matching if there are multiple matches and have users come in later and manually add?

![image](https://user-images.githubusercontent.com/57462572/97721533-8ba28580-1a97-11eb-825d-0ee601c971b6.png)

Please let me know if you have any clarifying questions!

Have a great weekend!

Mike

**Comment by Scarrien** [comment]
Closed by merge #212
