### ISSUE TITLE
Create core Reports and Dashboards to be included in Summit Events package

### ISSUE THREAD

**Issue by jimhubert** [SFDO-Community/Summit-Events-App#216]
During the September 2020 Open Source Sprint a group of users created a list of core reports and dashboards that need to be added to the Summit Events package.  This purpose of this issue is to create these reports and dashboards. 

Here is a link to the reports and dashboards that were selected during the September 2020 Open Source Sprint that need to be built:
https://docs.google.com/spreadsheets/d/1n2v_CT4Jmp_Icf3mo-UnuTEvpLVyDsofiBXdZBB9F7c/edit#gid=673625960

Note that the Custom Report Type edits and new Custom Report Types that are a pre-req for this work were added to the Summit Events package .011 in October 2020, so we are ready to start building the reports and dashboards whenever people are available to do this.

**Comment by rdblake21** [comment]
Reports are included
