### ISSUE TITLE
Need More than 5 Optional Fields available in Events object

### ISSUE THREAD

**Issue by jimhubert** [SFDO-Community/Summit-Events-App#219]
Currently Summit Events has 5 optional fields available on each Event record; however there are use cases where more than 5 fields are needed.  Need to either 1) add more fields (an additional 5??) or 2) Build a method that allows an Admin to add however many additional fields they need.

**Comment by tcdahlberg** [comment]
Included in beta release 0.27.0.1

**Comment by tcdahlberg** [comment]
Included in production release 0.27.0.1
