### ISSUE TITLE
Guest User Update - Spring '21 "fix"

### ISSUE THREAD

**Issue by rdblake21** [SFDO-Community/Summit-Events-App#222]
**Challenge:** In Winter '21, there was an update to Guest User access that removed "View All", "Delete" and "Edit" access.  The Guest User is not limited to just Create and Read access.  Summit Events is utilizing the Guest User for Event Registrations. This is intentional to allow the general public to sign up for events without requiring authentication at any point.  During the guest registration process, there is a page architecture (attached) that involves editing a started event registration record as well as related appointments where they may be creating, deleting and editing those appointments.  The appointments are a shopping cart like feature that builds an event itinerary for the registrant.  In addition, there is a self-cancellation feature that allows the individual to cancel their registration without involving direct interaction with the organization or the barrier of logging in to cancel.  This process involves editing the record, though the status change is triggered by the action of selecting a link.
 
Without edit on the Event Registration object, SEA will not let you go back via the previous button and edit the first page even though we’re making edits through "system mode." It appears we’re loosing access to the guest records being created when we post to the next page. While one would think that changing the creating process would solve for this, there is validity to capturing information while in a started status. 
 
The initial creation of the Event Registration happens on the submit/next of the first page.  If there are no pages after this, the record is created and put into a Registered status.  If there are pages that follow the first because of appointments (or payments in the future), the event registration is put into a “Started” status allowing for follow up and outreach if needed.  It also allows for a sort of RFI, which is highly valued for Admissions & Recruitment.

**Expected Outcome:** No disruption to the event registration with the ability for the form to change and be updated until the final submit.  Guest User would ideally hold the create access until the final stage of the registration process

![image](https://user-images.githubusercontent.com/25934611/99424034-d2c9ac80-28c6-11eb-8fbc-2b4c7a15df55.png)

**Comment by rdblake21** [comment]
@tcdahlberg I was testing the reg_delete_recreate and I was able to get through the Registrsation seamlessly, going back and forth, making changes and updating the record.  With the method you created, will we see a change in the Event Registration record ID or will it retain that ID throughout?

I did not notice the record ID changing which is totally fine, but wanting to clarify how the process works and what is getting created/deleted/created again.

**Comment by tcdahlberg** [comment]
On 11/19/2020 @rdblake21 and @tcdahlberg attended a [Trailblazer Community - Guest User Security Office Hours](https://register.gotowebinar.com/rt/2998232275027204611) where we were able ask our guest user questions and issues about Summit Event Apps. The Salesforce expert was able to affirm our approach to current and upcoming guest user restrictions. Namely:

- In our Visualforce Page controllers creating "with sharing" construct class for the logic of the page.

- With discipline passing our update DML work to a sub class that is flagged "without sharing" essentially doing this work in "system mode."

- Using an encrypted cookie to maintain our id information across pages (They seemed impressed with this notion as they had been recommending maintaining this through a URL parameter).

With the approval of our method the question remained why were were experiencing the inability to update on the registration page. The following suggestion was made:

- After the registration record is initially queried on the registration page controller (using the id maintained in the encrypted cookie) we remove/null the id from the record in memory and store the id in a variable for later. 

- When doing the update work in the "without sharing" sub class we re-apply the id to the registration record. 

This approach ended up working. Though our Salesforce expert was mystified about why we might need to do this.

This approach was somewhat stealthily applied in pull request #234.

**Comment by tcdahlberg** [comment]
#234 closes this issue.
