### ISSUE TITLE
Add Payment Architecture to Master Branch and Package

### ISSUE THREAD

**Issue by jimhubert** [SFDO-Community/Summit-Events-App#223]
Thad built the core architecture for payments in UST Events several months ago, but this architecture is in a stale branch that has not been added to the Master branch or the Summit Events package yet.  Getting these objects and fields into the package is a pre-req for people to be able to build their own payment integrations with SEA such as https://github.com/SFDO-Community-Sprints/Summit-Events-App/issues/29.

Per a November 9 meeting with Thad, here are the architecture items to be moved to the Master branch and package:
* Objects: Summit Events Fees, Summit Events Payments, Summit Events Fee Attributes 
* New Fields for payments on the following objects: Events, Instance, Appointments objects
* Add code to the "Submit" class so that inputs/outputs from custom code by users in the "Payment" class can be processed 
* Custom Setting for payment processing credentials to be stored
* Permission Set edits to view new objects and fields
* Recipe:  Move payment logic for TouchNet payments Thad wrote that is currently in the Submit class to a new "Payment" class

**Comment by jimhubert** [comment]
@tcdahlberg This is the last item left in the November 2020 release sprint, anything I can do to help get this one across the finish line?

**Comment by tcdahlberg** [comment]
@jimhubert, the following has been accomplished on the  [payment_object_architecture](/SFDO-Community-Sprints/Summit-Events-App/tree/payment_object_architecture) branch and are ready for testing:

* Objects: Summit Events Fees, Summit Events Payments, Summit Events Fee Attributes
* New Fields for payments on the following objects: Events, Instance, Appointments objects
* Permission Set edits to view new objects and fields
* Optional donation visualforce page and settings have been added
* Rudimentary layouts of new objects (Payment object doesn't have one yet as I do not receive a gateway response)

***Note the payment_object_architecture branch has been merge with the guest user fix branch with the assumption that both will be rolled into master at a similar time***

Please test and let me know your impressions. Things to pay attention to:

* Object layouts
* Field naming that doesn't make sense
* Missing configuration 
* Functionality of fee collecting on the event

Things missing:

* Any connection to a gateway
* A method for triggering a gateway connection on the submit page
* Storage for credentials

The above may be out of scope for this release
