### ISSUE TITLE
Why not include unpackaged metadata?

### ISSUE THREAD

**Issue by jacebryan** [SFDO-Community/Summit-Events-App#23]
Organizations could benefit from having access to unpackaged metadata - especially if the packaged options don't represent all possible use cases.

For example: There are 3 packaged Record Types included for Event:

- Graduate
- UDAR (seems specific to the UST)
- Undergraduate

I'm curious as to how these record types would translate for a K-12 institution.

**Comment by tcdahlberg** [comment]
Record types have been removed in the latest version of the master branch.
