### ISSUE TITLE
Date crumb has year issue when close to the end of the year

### ISSUE THREAD

**Issue by walt0019** [SFDO-Community/Summit-Events-App#232]
While testing a SEA report in Metecho, I changed the date of an instance so it fell just inside a 30 day window.  While the Event Instance Date, Event Instance Start Date and Event Instance End Date was 12/29/2020 the Event Instance Date Time Formatted field that appeared on the registration page was in 2021 and read "Tuesday, December 29, 2021, 8:00 AM - 3:30 PM CST."  So all was correct except the year.  
![image](https://user-images.githubusercontent.com/57462572/100659080-b5103480-3315-11eb-9771-8d7a4cc42890.png)  
![image](https://user-images.githubusercontent.com/57462572/100659150-d113d600-3315-11eb-9886-f931e5557b47.png)

**Comment by jimhubert** [comment]
@rdblake21 @tcdahlberg This issue will impact people at the end of the calendar year, I would like to add this to the December sprint https://github.com/SFDO-Community-Sprints/Summit-Events-App/milestone/2 and have @Scarrien work on this.  Are you ok with adding this to the December sprint?

**Comment by tcdahlberg** [comment]
This issue is fixed in #243 and is going to shortly be rolled into master. Thanks!
