### ISSUE TITLE
facing issues for installation in developer Sandbox

### ISSUE THREAD

**Issue by akkibaddi** [SFDO-Community/Summit-Events-App#238]
@rdblake21 and team any help is highly appreciated. We are trying to evaluate this for our events solutions and also want to contribute to this repo going forward.

thanks!

i am trying to install as mentioned in wiki and facing these below errors after cloning the repo.

Contacts_with_Summit_Events_Registrations | Custom Report Type | 0 | 0 | Could not find field CleanStatus in table Contact
-- | -- | -- | -- | --
SummitEventsReports/Registrations_Next_7_Days_GgD | Report | 0 | 0 | filterlanguage: Invalid value specified: 1.
SummitEventsReports/Registrations_Next_30_Days_Yzh | Report | 0 | 0 | filterlanguage: Invalid value specified: 1.
SummitEventsReports/New_Summit_Events_Registrations_Report_BeP | Report | 0 | 0 | filterlanguage: Invalid value specified: 1.
SummitEventsReports/In_Progress_Registrations_dVb | Report | 0 | 0 | filterlanguage: Invalid value specified: 1.
SummitEventsReports/Started_Registrations_RA0 | Report | 0 | 0 | filterlanguage: Invalid value specified: 1.
SummitEventsReports/Todays_Event_Registrations_AJD | Report | 0 | 0 | filterlanguage: Invalid value specified: 1.
Admin | Profile Settings | 0 | 0 | Unknown user permission: FieldServiceAccess

**Comment by tcdahlberg** [comment]
Hi @akkibaddi,

It looks like a profile got in the mix. I'll see if I can't fix the master branch up for you this morning.

Thanks,
Thad

**Comment by tcdahlberg** [comment]
Hi again @akkibaddi,

I removed the profile from the master branch and was able to spin up a scratch org. Can you confirm this on your end? if you have a branch made you may have to git merge orgin/master from your branch (or start a new branch from master)

Thanks!

**Comment by akkibaddi** [comment]
Hi @tcdahlberg thanks for removing profile, looks like in Developer Sandbox we might need to have 
Data.com stuff enabled and Translation Work bench enabled to over come report, report type errors mentioned above.

I think it would be great to update wiki or remove that dependency in meta data. 

Though I figured how to enable translation work bench in sandbox, I couldn't figure out how to turn on Data.com ( i think this is related to some licensing)

**Comment by tcdahlberg** [comment]
@akkibaddi,

Interesting. I hadn't run across that dependency before. Our dev hubs must define the licensing our scratch orgs have and I hadn't run into that issue.

As far as reports and their dependencies go I am going to refer this the @jimhubert as I think he is leading up this team (correct me if I'm wrong Jim). My preference would be to have the bar to using Summit Events as low as possible in Salesforce licensing. Jim may know better about this situation, though.

Thanks for joining in on the work @akkibaddi!

**Comment by Scarrien** [comment]
@jimhubert and I have removed the language filter from the reports so Translation Workbench does not have to be enabled, and removed the "CleanStatus" field on the Contact from the "Contacts with Summit Events Registrations" report type.

**Comment by jimhubert** [comment]
@akkibaddi As mentioned above by @Scarrien the two reporting dependency issues you reported above have been resolved.  Please test in your Developer Sandbox and confirm.  Thanks!

FYI @tcdahlberg @walt0019

**Comment by akkibaddi** [comment]
Hi @jimhubert yes its succeeded ! thanks for fixing that up :)
