### ISSUE TITLE
Summit Event record types all default to Graduate Event Layout

### ISSUE THREAD

**Issue by jacebryan** [SFDO-Community/Summit-Events-App#25]
There are 3 record types that come with the Summit Events object:

- Graduate
- UDAR
- Undergraduate

There are 3 page layouts that come with the Summit Events object:

- Graduate Event Layout
- UDAR Event Layout
- UG Event Layout

Will the process of assigning the correct page layouts be included as part of setup/configuration documentation?

**Comment by rdblake21** [comment]
This is being completed in #35
