### ISSUE TITLE
Need Standard Duplicate Rule

### ISSUE THREAD

**Issue by rdblake21** [SFDO-Community/Summit-Events-App#250]
In testing that Contact Matching Process, there is a picklist field on the Event Object field "Contact Creation Duplicate Rule
" called "Summit Events Contact Creation".  To avoid confusion, there should be a standard Duplicate Rule as there is already a packaged Matching Rule - Summit Events Contact Creation matching rule.

Having the standard will give guidance, but make it more out of the box ready.  This should be loaded in an active status to avoid additional confusion in package setup since there is already a value created.

**Comment by rdblake21** [comment]
Created the Duplicate Rule for a Summit Event standard to match the value that already exists on the Summit Event object.

Testing to see if "sort order" is necessary to have or if it will populate automatically on the creation of the org itself.

**Comment by rdblake21** [comment]
Sort order is a required field.

Need to test if the number is set to something that exists if it changes the order or reverts to the last spot

**Comment by jimhubert** [comment]
Ryan, we built this same duplicate rule several months ago but learned it
can't be added to.the managed package.

**Comment by rdblake21** [comment]
After reading forums and testing, adding a standard duplicate rule will create issues for future users.  From what I can tell, you are unable to deploy duplicate rules where the sort order assumes the last position.  Setting any sort order on a managed packaged (or unmanaged) will create conflict in the orgs existing duplicate rule order.

I'm suggesting we remove the current picklist value on the Summit Event Object field "Contact Creation Duplicate Rule" with the value of "Summit Events Contact Creation", so the value isn't an option within the package.

This could be done by removing the value from the dependent picklist since the field requires a value.

Thoughts?  Goal is to eliminate confusion and assumed functionality without setup.  Open to making documentation highlight the need for this step if that seems the best way to do it.

**Comment by rdblake21** [comment]
Better captured in #279 so closing this issue
