### ISSUE TITLE
Should not be able to enter end date that is earlier than start date on event instance

### ISSUE THREAD

**Issue by dwhitig** [SFDO-Community/Summit-Events-App#254]
I created an event instance with a start date that was after the end date.  It did not give me any warning but when I went to view the instance page, I got a nondescript error.  I'll add print screens.

Should validate that end date/time is greater than or equal to start date/time.

![image](https://user-images.githubusercontent.com/4521914/103418230-c8ecc780-4b5b-11eb-88a2-8978f4446041.png)

Believe this is what is causing this problem:
![image](https://user-images.githubusercontent.com/4521914/103418406-7cee5280-4b5c-11eb-8bf2-cd5cab24003d.png)

**Comment by JohnnyMac99** [comment]
Due to the fact that the Date & Time fields are separate, there needs to be 2 validations rules:
1. End Date must be >= Start date
2. IF (Start Date = End Date), End Time must be > Start Time, else it doesn't because you can end at a different time on a future date
