### ISSUE TITLE
Help Text - Type-o in Registration Email Restriction help text on parent event page

### ISSUE THREAD

**Issue by dwhitig** [SFDO-Community/Summit-Events-App#255]
There is a Type-o in Registration Email Restriction help text on parent event page.  There is an "s" missing on the end of the word Status.

![image](https://user-images.githubusercontent.com/4521914/103418827-5df0c000-4b5e-11eb-90be-512ce8012d7f.png)

**Comment by JohnnyMac99** [comment]
Simple Fix - just need to get sprinters setup with Metecho or ensure they know how to do a pull request for the change.

Same typo exists in the Description field
