### ISSUE TITLE
Move wiki images into the wiki repo

### ISSUE THREAD

**Issue by jhilyard** [SFDO-Community/Summit-Events-App#273]
Others may disagree, but I would prefer not to get commit messages when images are uploaded for use in the wiki.
The wiki is itself a git repo - https://github.com/SFDO-Community-Sprints/Summit-Events-App.wiki.git
You can see the clone URL at the bottom right of the wiki home page.
We can move /images in the main repo into /images in the wiki repo -- this will also simplify all the markdown links to just /images/whatever.jpg - no need for a protocol or hostname.
For folks who want a GUI to upload images to the wiki, use the Github desktop app to clone the wiki repo.

**Comment by jhilyard** [comment]
I've copied all the images to /images in the wiki and updated all the image URL references in all the wiki pages to use relative references to the local images folder.
I've also copied the /docs/*.md files to the wiki with the prefix zdocs- for now to make them show up at the bottom. This is kind of a separate decision from getting images out of the repo - is there a need for docs in the main repo or do those files just pre-date the wiki?
At this point nothing I've done has forced a new workflow on others - the next step would be a branch to remove the /images folder in the main repo and possibly /docs as well, which would require some buy-in that folks will use a git client like Github Desktop to upload images to the wiki in the future.

**Comment by jhilyard** [comment]
Here's a screenshot of github desktop connected to the wiki repo showing the "show in Finder" button which opens the folder you've cloned the repo to -- at which point you can click into the images subfolder, paste/drag in whatever images you want, then go back to github desktop and add a description and commit/push to upload the images.
<img width="976" alt="Github desktop show in finder" src="https://user-images.githubusercontent.com/2307684/107695538-c1522f80-6c7e-11eb-95f4-59eefbb12db2.png">

**Comment by jhilyard** [comment]
Github Desktop won't let you clone the wiki repo in its UI. You have to go to the command prompt in a desirable "parent" folder like Documents\Github\ and type `git clone https://github.com/SFDO-Community-Sprints/Summit-Events-App.wiki.git` and then in Github Desktop choose "open local repository..." and choose the Documents\Github\Summit-Events-App.wiki folder. From then on it's quite easy to add images using the "show in Finder/Windows Explorer" button, then type your commit summary and hit the "commit to master" button. Whether installing Github Desktop results in git being available from the command line is another question...
"What's the benefit of simpler image URLs" -- mostly it just benefits developers editing markdown in VS Code, or folks editing image urls without using the "insert image" button, which probably isn't non-developers. Developers using a text editor like VS Code to edit documentation in markdown have a much better reading experience not having image urls that wrap multiple lines -- we can right-click an image in the files left-nav of VS code and pick "copy relative path" and paste it straight into the markdown. For most folks writing from the browser WYSIWYG, there isn't a benefit on URL side.
As mentioned, there is a benefit that anyone with write access to the wiki can upload their own images without needing a main repo committer to approve a pull request to the main repo.
As Ryan mentioned, adding images to comments in a persistent "Wiki Images Issue" (like this issue could be!) is another way to get Github to host them outside the main repo.

**Comment by tcdahlberg** [comment]
Closing this issue as we are moving documentation to a seperate GitHub pages repo.

https://sfdo-community-sprints.github.io/summit-events-app-documentation/docs/Getting-Started/Installing/
