### ISSUE TITLE
Make Out of the Box Custom Metadata Contact Matching Method a more generic term

### ISSUE THREAD

**Issue by dwhitig** [SFDO-Community/Summit-Events-App#281]
In order to setup Matching you are required to select a Custom Metadata Contact Matching Method.  Right now the only option is called Admissions.  I'm guessing that this was for St. Thomas.  If it is required can we rename the one that is installed out of the box to be a more generic term like Summit Events Default (or something similar)?

I'm assuming that this is also the same Admissions you need to pick for the Contact Matching Method field when you are creating a new Custom Meta Data entry.

**Comment by rdblake21** [comment]
Additional values were added as we learned more can't be added once installed.  This should be solved for as there are more generic options to allow for several to be utilized, not just admissions.
