### ISSUE TITLE
Two fields called Registrant State Fields on Registration object could be confusing

### ISSUE THREAD

**Issue by dwhitig** [SFDO-Community/Summit-Events-App#282]
I understand that one is a text field and one is a picklist field but having two fields with the Exact same name can be confusing when creating reports or choosing items to display in related lists.  Not sure what can be done about this but just an observation.

[Two Registrant State Fields.pdf](https://github.com/SFDO-Community-Sprints/Summit-Events-App/files/5972639/Two.Registrant.State.Fields.pdf)

**Comment by Imanuelc112** [comment]
https://github.com/SFDO-Community-Sprints/Summit-Events-App/issues/282#issue-807317310

**Comment by rdblake21** [comment]
Update field label to reflect the Global Picklist nature of one of the fields.
