### ISSUE TITLE
Provide ability to filter a duplicate rule so it only runs when Summit Events Contact Matching creates a Contact 

### ISSUE THREAD

**Issue by jimhubert** [SFDO-Community/Summit-Events-App#286]
User Story from conversation with @dwhitig and @walt0019 on Feb 12 : 
"As a Salesforce Admin I need a way to restrict the duplicate rule used by Summit Events Contact Matching so it only runs when Summit Events is attempting to create a new Contact so that this duplicate rule does not run when a Contacts not created by Summit Events is added to Salesforce."

In other words, the condition on the duplicate rule only needs to run when creating Contacts from Summit Events and not editing Contacts from Summit Events (as Summit Events contact matching does not edit Contacts, it only matches or creates them).

**Comment by jimhubert** [comment]
@Scarrien Here is my proposed solution for this issue, what do you think?
1) Create a new checkbox field on the Summit Events Registration object called "Contact Created by Summit Events" with default value of False.
2) Add logic to the Contact Matching code that populates this new field with a value of True when a Contact record is created
3) Add section in Contact Matching documentation showing how an admin can add a condition to a Duplicate Rule using the "Contact Created by Summit Events" field = True so the duplicate rule will only run when Summit Events attempts to create a new Contact record. (Resource to start with on this is https://trailblazers.salesforce.com/answers?id=9063A000000poWpQAI but we can add a custom screenshot of this field being used as a condition)

**Comment by Scarrien** [comment]
This works, the one thing I would add to the documentation is I'd recommend that the duplicate rule be set to only run "on create" (uncheck the "on edit" checkboxes). This would make sure the duplicate rule only runs in the exact case we want it to.
