### ISSUE TITLE
Payment Processes (Touchnet Payment)

### ISSUE THREAD

**Issue by rdblake21** [SFDO-Community/Summit-Events-App#29]
Subtask | Assigned User | Complete?
--------- | ---------------- | -----------
Promo Codes |  User |

**Comment by jhilyard** [comment]
I tried to merge master to the feature/29 (TouchNet) branch but after slogging through scores of merge conflicts without the benefit of SObject Cache refreshes I hit a wall of cci errors. I think a fresh start from master is needed. Package scope architectural decisions are needed before a lot of code gets written. Maybe not a good task for the September sprint after all.

**Comment by tcdahlberg** [comment]
Included in beta release 0.27.0.1

**Comment by tcdahlberg** [comment]
Included in production release 0.27.0.1
