### ISSUE TITLE
Guest Management

### ISSUE THREAD

**Issue by rdblake21** [SFDO-Community/Summit-Events-App#30]
Subtask | Assigned User | Complete?
--------- | --------------- | ------------
Table Assignments | User | 
Company Purchases | User |

**Comment by jimhubert** [comment]
@walt0019 @jhilyard This is an existing issue in GitHub for Summit Events where you can add the requirements for Guest Management functionality that you posted in the Power of Us Hub.

**Comment by rdblake21** [comment]
Closing because it's captured in #226 and this one has not context
