### ISSUE TITLE
Add Time Zone in the Event Details of the Registration Page

### ISSUE THREAD

**Issue by walt0019** [SFDO-Community/Summit-Events-App#312]
When working with Donna, we noticed the time zone appears within the breadcrumb ribbon on the top of the registration page but was not in the Event Details on the page.  Can this data point be added within the Event Details too?

**Comment by walt0019** [comment]
![Summit Events Time Zone](https://user-images.githubusercontent.com/57462572/124035506-3e7a0900-d9c2-11eb-90e6-194a8a5f64ef.jpg)
Screenshot

**Comment by rdblake21** [comment]
This has been added to the latest release!
