### ISSUE TITLE
Admin - Initial Setup Documentation & Configuration

### ISSUE THREAD

**Issue by rdblake21** [SFDO-Community/Summit-Events-App#33]
Documentation needed regarding instructions for how to set all of the fields on the "event" object

- Record type - Need create a standard Record Type for page layout
-- Single standard Master Record Type, update and clean up the Page Layout #34 

- Template -  for Site itself #36 (With standardization, documentation may be limited, but should be focused toward branded to align with School)

- Event type - Define and determine values

- Location type - Define and document.  What are standards that may be globally used.  What does this control?

- Audience - Need setup instructions with documentation of what this control

- Event sponsor - What is this?  Define and articulate process to input what "Event Sponsors"

- Academic program list - Related Object #37 (Documentation focused on connecting existing object or fields within the object and or records that need to be created)

- Setting up Schools to be seen on event registration page

Refer to #90 as a related task
Refer to #92 as a related task

**Comment by jimhubert** [comment]
Refer to #90 as a related task

**Comment by deanernzen** [comment]
Google Document - [https://docs.google.com/document/d/1KsU8HtFZdy8sQWunmp3ztOYQTOa8KkoSpzHuYGUnDqE/edit?usp=sharing](url)

**Comment by rdblake21** [comment]
#90 is a duplicate and they cover the same items.  Additional and future notes referenced on the Wiki article.
