### ISSUE TITLE
Academic Programs as a Related Object

### ISSUE THREAD

**Issue by rdblake21** [SFDO-Community/Summit-Events-App#37]
With the focus on Education, there is functionality to relate events to Academic Programs. These would be managed in an object and records to be created based on the users desired functionality.

Need to create the related objects and/or connect to EDA functioning objects.

**Comment by jimhubert** [comment]
I believe we should use the EDA functionality for Academic Programs - "An Academic Program in EDA is simply an Account with a specific record type called 'Academic Program'."  https://powerofus.force.com/s/article/EDA-Create-Academic-Programs-and-Program-Enrollments

**Comment by rdblake21** [comment]
THis is related to #14.  Closing this one to utilize #14
