### ISSUE TITLE
Summit Event Email

### ISSUE THREAD

**Issue by rdblake21** [SFDO-Community/Summit-Events-App#73]
While the overall Summit Event Email object needs some love/enhancements.  There is a current bug in that when you go to the "Letterhead Definition" and select your options, when you hit "close", it closes Salesforce.  When you select "Save" the save function doesn't work.

This likely hasn't been noticed because you can't email out of a scratch org. This may be specific to the scratch or not having an Org wide email address setup prior to this step.

* Need to make sure that the "Close" button reverts you back to the Event Email record associated to it.
* Need to make sure that the "Save" button saves changes and reverts you back to the Event Email record associated to it.

@tcdahlberg

**Comment by rdblake21** [comment]
Closed with #387

**Comment by tcdahlberg** [comment]
Included in beta release 0.27.0.1

**Comment by tcdahlberg** [comment]
Included in production release 0.27.0.1
