### ISSUE TITLE
Rebranding tidbit: ustadmissions in URLs/code

### ISSUE THREAD

**Issue by jhilyard** [SFDO-Community/Summit-Events-App#77]
Find in files "ustadmissions"

22 results - 3 files

force-app\main\default\classes\SummitEventsRestAdmissions_TEST.cls:
  65          RestResponse res = new RestResponse();
  66:         req.requestURI = '/services/apexrest/ustadmissionsrest';
  67          req.params.put('type', type);

  75          RestContext.response = res;
  76:         SummitEventsRestAdmissions.getUstAdmissionsRest();
  77      }

force-app\main\default\classes\SummitEventsRestAdmissions.cls:
    5  
    6: @RestResource(urlMapping='/ustadmissionsrest/*')
    7  

   24      @HttpGet
   25:     global static void getUstAdmissionsRest() {
   26          RestResponse res = RestContext.response;

   39              if (feedType.toLowerCase() == 'highschool') {
   40:                 // https://COMMUNITY_SUB_DOMAIN.force.comservices/apexrest/ustadmissionsrest.json?type=highschool
   41                  serializedJSON = JSON.serialize(getSchools('High School'));

   43              } else if (feedType.toLowerCase() == 'college') {
   44:                 // https://COMMUNITY_SUB_DOMAIN.force.comservices/apexrest/ustadmissionsrest.json?type=college
   45                  serializedJSON = JSON.serialize(getSchools('College'));

   47              } else if (feedType.toLowerCase() == 'states') {
   48:                 // https://COMMUNITY_SUB_DOMAIN.force.comservices/apexrest/ustadmissionsrest.json?type=states
   49                  serializedJSON = JSON.serialize(getObjDefMap(Contact.MailingState.getDescribe()));

   51              } else if (feedType.toLowerCase() == 'cities') {
   52:                 // https://COMMUNITY_SUB_DOMAIN.force.comservices/apexrest/ustadmissionsrest.json?type=cities
   53                  serializedJSON = JSON.serialize(getCityList());

   55              } else if (feedType.toLowerCase() == 'countries') {
   56:                 // https://COMMUNITY_SUB_DOMAIN.force.comservices/ustadmissionsrest.json?type=countries
   57                  serializedJSON = JSON.serialize(getObjDefMap(Contact.MailingCountry.getDescribe()));

   59              } else if (feedType.toLowerCase() == 'gradschools') {
   60:                 // https://COMMUNITY_SUB_DOMAIN.force.comservices/apexrest/ustadmissionsrest.json?type=gradschools
   61                  serializedJSON = JSON.serialize(getSchools());

   63              } else if (feedType.toLowerCase() == 'gradprograms') {
   64:                 // https://COMMUNITY_SUB_DOMAIN.force.comservices/apexrest/ustadmissionsrest.json?type=gradprograms
   65                  serializedJSON = JSON.serialize(getGradPrograms());

   67              } else if (feedType.toLowerCase() == 'ugmajors') {
   68:                 // https://COMMUNITY_SUB_DOMAIN.force.comservices/apexrest/ustadmissionsrest.json?type=ugmajors
   69                  serializedJSON = JSON.serialize(getUGMajors());

   71              } else if (feedType.toLowerCase() == 'ugactivities') {
   72:                 // https://COMMUNITY_SUB_DOMAIN.force.comservices/apexrest/ustadmissionsrest.json?type=ugmajors
   73                  serializedJSON = JSON.serialize(getActivities('Clubs and Organizations'));

   75              } else if (feedType.toLowerCase() == 'ugclubsports') {
   76:                 // https://COMMUNITY_SUB_DOMAIN.force.comservices/apexrest/ustadmissionsrest.json?type=ugclubsports
   77                  serializedJSON = JSON.serialize(getActivities('Intramurals/Club Sports'));

   79              } else if (feedType.toLowerCase() == 'ugvarsitysports') {
   80:                 // https://COMMUNITY_SUB_DOMAIN.force.comservices/apexrest/ustadmissionsrest.json?type=ugvarsitysports
   81                  serializedJSON = JSON.serialize(getActivities('Varsity Sports'));

   83              } else if (feedType.toLowerCase() == 'ugmusic') {
   84:                 // https://COMMUNITY_SUB_DOMAIN.force.comservices/apexrest/ustadmissionsrest.json?type=ugmusic
   85                  serializedJSON = JSON.serialize(getActivities('Music'));

   88                  /*serializedJSON = JSON.serialize(getObjDefMap(Major__c.Areas_of_Interest_for_program_finder__c.getDescribe()));*/
   89:                 // https://COMMUNITY_SUB_DOMAIN.force.comservices/apexrest/ustadmissionsrest.json?type=areaofinterest
   90  
   91              } else if (feedType.toLowerCase() == 'degree') {
   92:                 // https://COMMUNITY_SUB_DOMAIN.force.comservices/apexrest/ustadmissionsrest.json?type=degree
   93                 /* serializedJSON = JSON.serialize(getObjDefMap(EnrollmentrxRx__Program_Offered__c.Degree_Level__c.getDescribe()));*/

   95              } else if (feedType.toLowerCase() == 'learningstyle') {
   96:                 // https://COMMUNITY_SUB_DOMAIN.force.comservices/apexrest/ustadmissionsrest.json?type=degree
   97                  /*serializedJSON = JSON.serialize(getObjDefMap(Major__c.Learning_Style_for_program_finder__c.getDescribe()));*/

  120          // Possible URL variables
  121:         // https://COMMUNITY_SUB_DOMAIN.force.comservices/apexrest/ustadmissionsrest.json?type=programfinder
  122          // any combination of the following parameters can be sent to the API request

  128          // &filter= <- comma separate list of text that the query will test against the name of the program, major, degree, learning style, and area of interest
  129:         // https://COMMUNITY_SUB_DOMAIN.force.comservices/apexrest/ustadmissionsrest.json?type=programfinder&interest=&degree=&style=&schoolId=&filter=
  130  

force-app\main\default\staticresources\SummitEventsAssets\js\register.js:
  187      ChosenProcess[type] = $.ajax({
  188:         url: "/services/apexrest/ustadmissionsrest",
  189          data: {'type': type, 'filter': filter},

**Comment by tcdahlberg** [comment]
Hi @jhilyard, I am actually removed this whole class as part of the #74 issue. This class really has nothing to do with Summit Events. It was develop to expose admissions counselors assignments based on school/region for St. Thomas' Web site. The branch 74-Remove-EDA-Dependency reflects this change. Good catch, and definitely an issue!

**Comment by tcdahlberg** [comment]
This class and test class have been removed from the code base.
