### ISSUE TITLE
Developers - Itinerary generation in base package 

### ISSUE THREAD

**Issue by tcdahlberg** [SFDO-Community/Summit-Events-App#86]
During the recent removal of EDA dependency in the project TDTM triggers needed to be removed. One of these triggers was responsible for generating requested and confirmed itineraries. Both generated off of appointments selected during registration. Requested happening on the status of "Requested" on the registration and confirmed itineraries on the confirmation of each of those appointments.  It may be possible to use a lighting flow with APEX actions to achieve this without creating triggers and a framework for those triggers.

## Possible enhancement ##

What appears on an itinerary comes off of the appointment object for the registration. What appeared in the generated itinerary was often debated and changed per event. Perhaps we could fulfill all requests with a simple template field on the umbrella event record. The template could reference any field that is on the appointment record (similar to how transactional emails are created with the registration record). A template could look something like this:

> Heading 1 | Heading 2 | Heading 3
> Appointment_Field__c | Appointment_Field__c | Appointment_Filed__c

The top line could be plain english headings with pipe separators. The bottom line could be field API names from the appointment object.

**Comment by rdblake21** [comment]
Working on in this branch - https://github.com/SFDO-Community-Sprints/Summit-Events-App/tree/AppointmentIntineraryGeneration

Was able to remove the TDTM aspects, rebuilding the trigger and adjusting the class.

Trigger is currently built/scoped to this process.
What existed in UST Events not exists in Summit Events

Looking at potential enhancements/updates for more formatting control.

**Comment by rdblake21** [comment]
Add additional field for individual meetings links on the Appointment.

App_Virtual_Meeting_URL__c - intended for individual appointment links should there not be one at the Registration level.  Could be utilized for breakouts with separate virtual meeting sessions (like a meet and greet, or presentations).

**Comment by tcdahlberg** [comment]
Included in beta release 0.28.0.1

**Comment by tcdahlberg** [comment]
Included in production release 0.28.0.2
