### ISSUE TITLE
Admin - Initial Configuration for Best Experience

### ISSUE THREAD

**Issue by rdblake21** [SFDO-Community/Summit-Events-App#90]
Documenting the Setup experience post install.  What does an Admin need to configure, setup, assign, etc for the best End User experience.  This is focused on docuementation.

Permissions Set
Picklist Values
Org-Wide Email Setup

**Comment by deanernzen** [comment]
Google Document - [https://docs.google.com/document/d/1KsU8HtFZdy8sQWunmp3ztOYQTOa8KkoSpzHuYGUnDqE/edit?usp=sharing](url)

**Comment by jimhubert** [comment]
@deanernzen @ShaynaStockton @DKlein-Smith I added a page to the wiki today titled  "0 – Steps To Do Before You Start Using Summit Events" that addresses this issue and #33 and is based on your work at the mini-sprint a few weeks ago.  Can you take a look at this page at https://github.com/SFDO-Community-Sprints/Summit-Events-App/wiki/0--%E2%80%93--Steps-To-Do-Before-You-Start-Using-Summit-Events and provide feedback?  Thanks.

**Comment by rdblake21** [comment]
Move to done as this is in the Wiki and seem complete.

Thank you, @jimhubert
