### ISSUE TITLE
Admin - Global Picklist Uses

### ISSUE THREAD

**Issue by rdblake21** [SFDO-Community/Summit-Events-App#92]
Where are Global Picklists being utilized, how do they need to be updated and are there other fields that should be leveraging global picklists

Can a standard picklist be changed to global post install (if not, articulate why one shouldn't do that).

Where are the picklist being utilized

**Comment by dwhitig** [comment]
@rdblake21 I think this needs a conversation as the documentation would be driven by the answers to the questions you are asking here.  Can you put this on as an agenda item on the next meeting?

**Comment by rdblake21** [comment]
Global picklists are able to be utilized and documented appropriately.
