### ISSUE TITLE
Developers - Core Package and functional Automation

### ISSUE THREAD

**Issue by rdblake21** [SFDO-Community/Summit-Events-App#93]
What within the Core Package needs to have certain automation developed now that TDTM is removed and there isn't an EDA or NPSP functionality.

- Triggered Emails
- Contact Matching process
- Others?

**Comment by MatthewBlanski** [comment]
What of this is essential for MVP here? If we're looking to make a package, perhaps it might be wise to isolate what is 'core' functionality and then work out automation from there.

**Comment by rdblake21** [comment]
Contact Matching is in the core.  Email may not need to be.  closing ticket
