### ISSUE TITLE
Admin - Documentation to Create Scratch Org with metecho

### ISSUE THREAD

**Issue by fdfriedrich** [SFDO-Community/Summit-Events-App#98]
Create documentation about how to use Metecho as an alternative tool to create a scratch org with Summit Events installed. Documentation could/should include: 

- Instructions from start to finish on how to get to Metecho, create an Org, naming convention best practices, and how to access the org once it's been created. 

- Add Metecho information to Support Tool Definition for Summit Events? https://github.com/SFDO-Community-Sprints/Summit-Events-App/wiki/Support-Tool-Definition-for-Summit-Events

**Comment by jimhubert** [comment]
Here is a link to the work that Farrah Friedrich and Elisa Landgraf did at the July 202 mini-sprint on this topic  https://docs.google.com/document/d/1WY2Dl_eHEGIdPTdYtqIXmwC_FD9kKRcK_nl2kPpWxWE/edit

**Comment by rdblake21** [comment]
Need to move to Wiki in Github, then will close ticket.

**Comment by rdblake21** [comment]
Added to the Wiki - https://github.com/SFDO-Community-Sprints/Summit-Events-App/wiki/Contribute-to-Summit-Events-with-Metecho
